trailingComma = "es5"
printWidth = 120
tabWidth = 4
semi = false
quoteProps = "consistent"

importOrder = ["^React$", "^next(.*)$", "<THIRD_PARTY_MODULES>", "^[./]"]
importOrderSeparation = false
importOrderSortSpecifiers = true
